// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ebj8LU_ybGPYT0q21ovOtRdRFDXAKog',
    appId: '1:212006075439:web:2554c126964b4a064d9ada',
    messagingSenderId: '212006075439',
    projectId: 'musicapp-156cc',
    authDomain: 'musicapp-156cc.firebaseapp.com',
    storageBucket: 'musicapp-156cc.appspot.com',
    measurementId: 'G-C00QH04X16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATjaV8NojQr2qnPDa1Yi23M8Qk06pHYCw',
    appId: '1:212006075439:android:33aba433f957fa054d9ada',
    messagingSenderId: '212006075439',
    projectId: 'musicapp-156cc',
    storageBucket: 'musicapp-156cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoN77iAH4j8cqVDiAtmJ1_kKi0_WgMgQc',
    appId: '1:212006075439:ios:2757d66fbc0f7e6f4d9ada',
    messagingSenderId: '212006075439',
    projectId: 'musicapp-156cc',
    storageBucket: 'musicapp-156cc.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoN77iAH4j8cqVDiAtmJ1_kKi0_WgMgQc',
    appId: '1:212006075439:ios:8b21cc08b97e26fe4d9ada',
    messagingSenderId: '212006075439',
    projectId: 'musicapp-156cc',
    storageBucket: 'musicapp-156cc.appspot.com',
    iosBundleId: 'com.example.musicApp.RunnerTests',
  );
}
